# -*- coding: utf-8 -*-
"""Generate sitemap.xml for all public content pages.

Usage:
  python tool/generate-sitemap.py
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

TOOL_DIR = Path(__file__).resolve().parent
if str(TOOL_DIR) not in sys.path:
    sys.path.insert(0, str(TOOL_DIR))

from lib.paths import ROOT  # noqa: E402

SITE_ORIGIN = "https://korea-guidebook.cloud"
OUT = ROOT / "sitemap.xml"

# Legacy / redirect stubs must not be indexed as separate URLs.
REDIRECT_MARKERS = (
    'http-equiv="refresh"',
    "http-equiv='refresh'",
    "location.replace(",
)

SKIP_DIR_PARTS = {
    "templates",
    "tool",
    ".git",
    "node_modules",
    "__pycache__",
    ".cache",
}


def is_redirect_page(html: str) -> bool:
    head = html[:4000].lower()
    return any(m.lower() in head for m in REDIRECT_MARKERS)


def to_loc(rel_posix: str) -> str:
    """Map repo-relative path to public absolute URL (custom domain at /)."""
    if rel_posix in ("", "index.html"):
        return SITE_ORIGIN + "/"
    path = rel_posix
    if path.endswith("/index.html"):
        path = path[: -len("index.html")]
    elif path.endswith("index.html"):
        path = path[: -len("index.html")]
    if path and not path.endswith("/"):
        path += "/"
    return SITE_ORIGIN + "/" + path.lstrip("/")


def priority_for(rel: str) -> str:
    if rel in ("", "index.html"):
        return "1.0"
    depth = rel.count("/")
    if depth <= 1:
        return "0.9"
    if depth == 2:
        return "0.8"
    return "0.7"


def changefreq_for(rel: str) -> str:
    if rel in ("", "index.html"):
        return "weekly"
    if rel.startswith("pages/foods/") or rel.startswith("pages/festivals"):
        return "weekly"
    return "monthly"


def collect_pages() -> list[str]:
    found: list[str] = []
    root_index = ROOT / "index.html"
    if root_index.is_file() and not is_redirect_page(root_index.read_text(encoding="utf-8", errors="ignore")):
        found.append("index.html")

    pages_dir = ROOT / "pages"
    if pages_dir.is_dir():
        for path in sorted(pages_dir.rglob("index.html")):
            rel = path.relative_to(ROOT).as_posix()
            parts = set(path.relative_to(ROOT).parts)
            if parts & SKIP_DIR_PARTS:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            if is_redirect_page(text):
                continue
            found.append(rel)

        # Important standalone HTML under pages (non-index), if any
        for path in sorted(pages_dir.rglob("*.html")):
            if path.name == "index.html":
                continue
            rel = path.relative_to(ROOT).as_posix()
            parts = set(path.relative_to(ROOT).parts)
            if parts & SKIP_DIR_PARTS:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            if is_redirect_page(text):
                continue
            # Skip obvious admin/tool fragments
            if re.search(r"(admin|template|scrape)", rel, re.I):
                continue
            found.append(rel)

    # Dedupe preserving order
    seen: set[str] = set()
    out: list[str] = []
    for rel in found:
        if rel not in seen:
            seen.add(rel)
            out.append(rel)
    return out


def write_sitemap(rels: list[str]) -> None:
    today = date.today().isoformat()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        f"  <!-- Generated by tool/generate-sitemap.py · {today} · {len(rels)} URLs -->",
    ]
    for rel in rels:
        loc = to_loc(rel if rel != "index.html" else "")
        lines.extend(
            [
                "  <url>",
                f"    <loc>{loc}</loc>",
                f"    <changefreq>{changefreq_for(rel if rel != 'index.html' else '')}</changefreq>",
                f"    <priority>{priority_for(rel if rel != 'index.html' else '')}</priority>",
                "  </url>",
            ]
        )
    lines.append("</urlset>")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    rels = collect_pages()
    write_sitemap(rels)
    print(f"Wrote {OUT.relative_to(ROOT).as_posix()} with {len(rels)} URLs")
    print(f"Origin: {SITE_ORIGIN}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
